# Generated by Django 3.0.3 on 2020-09-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
                ('RAM', models.IntegerField()),
                ('Processor', models.CharField(max_length=50)),
                ('Type', models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptop')], max_length=10)),
            ],
        ),
    ]
